pre-commit: Switch to markdownlint-cli
The old hook (markdownlint) threw the following error:

    ERROR:  Error installing mdl-0.13.0.gem:
    	mixlib-shellout requires Ruby version >= 3.0. The current ruby version is 2.7.0.0.

This could probably be fixed using language_version, but the new hook
has a newer markdownlint version as well.