CI: Switch to ubuntu:xenial from ros:kinetic
This hopefully fixes weird dependency problems like this one:

/opt/ros/kinetic/lib/liburdf.so: undefined reference to `rosconsole_bridge::RegisterOutputHandlerProxy::~RegisterOutputHandlerProxy()'